# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f911b507b803a3e90c11adbc8e06b6fdd9414021b187e00fe603d6ed2a34dd166a1e95ac12ba566bcd04b379b785486cf2579bdf95d98307ba67887b2cebb34
  fyber:
    appid: <%= ENV['FYBER_APPID'] %>
    ip: <%= ENV['FYBER_IP'] %>
    locale: <%= ENV['FYBER_LOCALE'] %>
    device_id: <%= ENV['FYBER_DEVICE_ID'] %>
    api_key: <%= ENV['FYBER_API_KEY'] %>

test:
  secret_key_base: b4f084c183faf181520db16aba80a2e9a4f40092f0e6df06e61ef49215c826f51708435af20165a068c6d0dfbccd8c306b53a8fab09ccf77cd8704f2f11ec498
  fyber:
    appid: 157
    ip: 212.45.111.17
    locale: de
    device_id: device_id
    api_key: e95a21621a1865bcbae3bee89c4d4f84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
